version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: local_mongo
    restart: always
    environment:
      # 실무 환경과 유사하게 루트 관리자 계정 설정
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password1234
      # 초기 생성할 데이터베이스 이름 (주의: 루트 계정으로 로그인 후 해당 DB를 사용하게 됨)
      MONGO_INITDB_DATABASE: employee_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db